Few fixes
valandil/wignerSymbols pull request #9
Opened 2024-04-19 11:25 UTC by ruthenium96

2024-04-21 18:01 UTC, joeydumont requested changes
Thanks for your contribution, it is appreciated! 

Please note the changes I suggested in the review.

2024-04-21 18:01 UTC, joeydumont commented on tests/CMakeLists.txt
Could you make the `add_directory(tests)` in the main CMakeLists.txt conditional on BUILD_TESTING being true instead? That way, we wouldn't skip tests when we actually want to test them, and armadillo becomes a dev dependency.

2024-04-23 08:41 UTC, ruthenium96 commented on tests/CMakeLists.txt
I made the requested changes in the last commit. Thank you for this suggestion!

2024-04-26 01:01 UTC, joeydumont approved these changes
Sounds good, thanks!

2024-04-26 01:02 UTC, merged